name: Remote Repo Build Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Remote Repo
        uses: actions/checkout@v4
        with:
          repository: dotnet/samples
          path: source

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        working-directory: source/core/console-apps/HelloWorld
        run: dotnet restore

      - name: Build
        working-directory: source/core/console-apps/HelloWorld
        run: dotnet build --configuration Release